### ISSUE TITLE
Filter commits for CI

### ISSUE THREAD

**Issue by rgieseke** [openscm/pymagicc#13]
https://www.appveyor.com/docs/how-to/filtering-commits/

**Comment by lewisjared** [comment]
What is the downside of running Appveyor every time?
Parallel question, but, what does it provide that Travis doesn't?

**Comment by rgieseke** [comment]
I just wanted to skip testing commits to Markdown files, where the can't be any changes reported. 

Travis (and I think Appveyor) check for `[skip ci]` in the commit message, but I often forget this, so it would be nice to have this automated.

Appveyor was included for testing on Windows -- ironically, due to a Windows specific omission with `subprocess` for some time Pymagicc didn't work on Windows, which is the only platform the binary supports ...

**Comment by lewisjared** [comment]
@rgieseke Can this be closed?

**Comment by rgieseke** [comment]
I haven't really got round to it, it would be useful to have (just now forgot with an image only commit to add [skip ci]):

https://github.com/travis-ci/travis-ci/issues/6301

Maybe something like this: https://github.com/dev-id/Magic-Spoiler/blob/8111a06ab6682e020169991d5e2aa4fa503d787f/preflight.sh

**Comment by lewisjared** [comment]
Ahh, now I see what you are trying to achieve! Some automated machinery which determines whether the CI is run or not.

**Comment by znicholls** [comment]
Given we're now using github actions, can we close?

**Comment by rgieseke** [comment]
With GitHub Actions one could use their filters 

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

or an action like

https://github.com/dorny/paths-filter

Up to you, feel free to close, i guess PRs that only touch Markdown or Docs are rare, so i'm not sure it's worth the additional complexity.

**Comment by znicholls** [comment]
> Up to you, feel free to close, i guess PRs that only touch Markdown or Docs are rare, so i'm not sure it's worth the additional complexity

My current feeling is just run everything every time, slightly more expensive but makes things much simpler.

**Comment by rgieseke** [comment]
Fully agreed, just leaving a note here, in case this is revisited in the future: currently GitHub Actions doesn't seem to support [skip ci]

https://github.community/t/github-actions-does-not-respect-skip-ci/17325/

There are some work-arounds but i guess it will happen in the future.
