### ISSUE TITLE
Parallel pymagicc

### ISSUE THREAD

**Issue by znicholls** [openscm/pymagicc#193]
**Is your feature request related to a problem? Please describe.**

It would be great if pymagicc could run MAGICC instances in parallel. 

**Describe the solution you'd like**

I think something like this would work https://stackoverflow.com/questions/16450788/python-running-subprocess-in-parallel

**Describe alternatives you've considered**

Writing something else, I have little idea about which libraries are out there however. 

**Additional context**

Discussing with @lewisjared, this shouldn't be too painful.

**Comment by lewisjared** [comment]
This is handled by openscm/openscm-runner
