### ISSUE TITLE
Move to using OpenSCMDataFrame

### ISSUE THREAD

**Issue by znicholls** [openscm/pymagicc#197]
**Is your feature request related to a problem? Please describe.**

At the moment our interface is a bit clunky to use. We could make it much easier by moving to using OpenSCMDataFrame's in the back end instead.

**Describe the solution you'd like**

Move to using OpenSCMDataFrame throughout pymagicc.

**Describe alternatives you've considered**

Create our own implementation.

**Additional context**

**Comment by znicholls** [comment]
@rgieseke @lewisjared I've attempted to address this in #198, #199, #200, #201, #202, #203 (they build on top of each other so hopefully all makes sense eventually).

There's a lot of dependencies which we're waiting on so the setup is a bit messier than would be ideal but hopefully these PRs should give us a start.

**Comment by rgieseke** [comment]
This probably needs an update with the OpenSCM rename to `ScmDataFrame`

**Comment by znicholls** [comment]
superceded by #295
