### ISSUE TITLE
Metadata handling in runs

### ISSUE THREAD

**Issue by znicholls** [openscm/pymagicc#248]
**Is your feature request related to a problem? Please describe.**

As it stands, we're writing out all our run parameters/config to `mdata.metadata["parameters"]`. `ScmDataFrame` doesn't know about this convention so we'd have to write custom wrappers in order to be able to use it properly.

**Describe the solution you'd like**

Given `ScmDataFrame` is built to handle metadata sensibly, we should really just be using its `set_meta` method. 

**Describe alternatives you've considered**

Custom wrappers around `MAGICCData`, maybe even a `to_scmdataframe` method. Seems like unnecessary mucking around.

**Additional context**

thoughts @lewisjared ?

**Comment by lewisjared** [comment]
Maybe it is better to add the functionality in openclimatedata/openscm#172 will be a better way of handling model parameters/metadata?

I would prefer not having 100 column index

**Comment by znicholls** [comment]
> Maybe it is better to add the functionality in [openclimatedata/openscm#172](https://github.com/openclimatedata/openscm/issues/172) will be a better way of handling model parameters/metadata?

Yep nice!

> I would prefer not having 100 column index

Haha fair. Out of curiousity, why exactly? If filtering does whatever you want anyway why does it matter?

**Comment by lewisjared** [comment]
While you can flatten the model parameters and timeseries into a single table, it makes it really opaque as to what is really happening. It's the so-called "Flat" data model which is one way of representing the data, but destroys the relationships between the entities (ModelRun, Timeseries, Parameter). 

Timeseries are unique to a model run (running the model with two different sets of parameters will result in different numbers), but many models can have a given value of parameter. Conflating the data which index a given timeseries and the everything about a model run complicates things. A clearer way is to index a unique identifier for a model run and the unique parameters of the timeseries (variable, unit, region) that way you guarantee that all rows are unique. In a second table the relationship between model run and parameters is tracked. You can still map between parameters and timeseries, but that mapping occurs via the unique model run identifier. I'll draw you a diagram.

**Comment by znicholls** [comment]
I think I get it, basically it just becomes a database where we have to have a unique key go between the two sets?
