### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by znicholls** [openscm/pymagicc#289]
@rgieseke can you make appveyor point at this new url?

**Comment by rgieseke** [comment]
I'd suggest you create a new account as `openscm` or we do the tests using GitHub Actions which also supports Windows!

**Comment by znicholls** [comment]
Beauty will do!

**Comment by rgieseke** [comment]
Which option?

**Comment by znicholls** [comment]
github actions

**Comment by znicholls** [comment]
Almost fixed by #293. Remaining problem is getting the notebooks passing on windows. Any interest @rgieseke or @lewisjared ?

**Comment by rgieseke** [comment]
If that's more of a problem of running/testing notebooks on Windows under CI i probably wouldn't spend too much time on it ... If there are changes in notebook output they are hopefully already caught by the Linux tests ...

**Comment by znicholls** [comment]
I had one failing in #293 and obviously don't have a windows machine so couldn't easily work out what was going on. In an ideal world we'd run both but not a problem I can easily solve right now.

**Comment by rgieseke** [comment]
There are trade-offs with testing everything everywhere ... time to finish CI, energy usage, what do we want to check with testing notebooks? They shouldn't get out-of-sync with the code is probably most important. If there were a mis-match with Windows output only, then this should be covered in regular tests i think.

**Comment by znicholls** [comment]
Beauty, will close then and we can open again in future if needed
