### ISSUE TITLE
Install broken with Pandas 1.2

### ISSUE THREAD

**Issue by rgieseke** [openscm/pymagicc#319]
https://github.com/openscm/pymagicc/actions/runs/451792013

This is due to https://github.com/hgrecco/pint-pandas/issues/51

In #318 i pinned Pandas to below 1.2

**Comment by rgieseke** [comment]
Pinned on scmdata >= 0.7.5 now

**Comment by znicholls** [comment]
New release and close?

**Comment by rgieseke** [comment]
Sounds like a plan!

**Comment by znicholls** [comment]
v2.0.0rc10
