### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by znicholls** [openscm/pymagicc#320]
AGPL licenses can be a pain for many users, how do we feel about moving towards a more permissive license (e.g. Apache 2.0)? Given that pymagicc wraps a non-commercial binary, there's no real commercial worries anywhere and the fix in licensing really needs to come from MAGICC (we're working on that, a proposal was recently accepted to take it open-source).

@rgieseke @lewisjared @swillner @matthiasmengel any objections (also hi!)?

**Comment by rgieseke** [comment]
If we switch to a permissive license i'd go for a simple one, i don't think the patents stuff in Apache license should be a problem while sciencing.

**Comment by znicholls** [comment]
> If we switch to a permissive license i'd go for a simple one

Simple meaning even simpler than Apache e.g. MIT?

**Comment by rgieseke** [comment]
Yes, BSD-2 or MIT probably.

**Comment by swillner** [comment]
ok

**Comment by matthiasmengel** [comment]
ok with me.

**Comment by rgieseke** [comment]
BSD-3 like the other OpenSCM tools is probably a good option them.
(I was thinking BSD-3 not being compatible with GPL but that's apparently only the case for GPLv2, in case it needs to be used with something GPLv3 later on)

The clause 3 is likely useful for the Pymagicc use-case.

https://opensource.stackexchange.com/questions/6319/how-is-the-bsd-gpl-compatible

**Comment by znicholls** [comment]
PR in #322
