### ISSUE TITLE
increase GHG response outside of scen

### ISSUE THREAD

**Issue by safiume** [openscm/pymagicc#324]
**Description**

Running pymagicc with custom SCENs often results in a sharp increase in RF and surface temp either just after all the specifically defined ghg values, or in an intermediate format that's been set via pandas and not hard defined by a scen.

**Failing Test**
https://github.com/hsbay/cdrmex/blob/dev/ONCtests.ipynb, screenshots show the transient, sharp increase then return to normal for GhGs, 
In the second to the last panel, Out [21], various gasses values increase despite the scen and modifications to pandas data frames defining the main MAGICC 6 gasses values to decrease. 

**Expected behavior**

The curves should have basic peak then decline, not have the double peak in the 2020-2030s.

**Screenshots**

![image](https://user-images.githubusercontent.com/4840719/107010435-2d96d580-674b-11eb-9200-78d6d2911e15.png)

**System (please complete the following information):**

 - OS: macOS
 - Pymagicc version 2.0.0rc8+19.g7aade1e.dirty
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)]

**Additional context**
I've uploaded my full sample code to the dev branch of CDRMEx for additional troubleshooting. Alternatively, if there is a workaround like hard define all pandas data frames to have the Fortran pure formatting, before running pymagicc that would work also.

**Comment by znicholls** [comment]
That's a MAGICC 'feature'. If you run it beyond the end of your SCEN file, it just assumes zero for all emissions hence the hump. You have to specify emissions for the entire run if you want to avoid this.

**Comment by safiume** [comment]
The MAGICC 6 feature of needing one to hard define the ending values to fully get MAGICC to stop calculating isn't what I'm seeing.
I'm seeing an increase in some of the gasses not defined in a SCEN from 2020-2030, whereas all the other 23 MAGICC ghgs decline during that time and continue to do so till 2050, and then are forced to 0 till 2100.

I shouldn't see the odd bounce back from 2020-2030 when all of that is defined to decline.
What's weird, is this is the same bounce that's at the end of RCP26PD.

**Comment by safiume** [comment]
I think I'm seeing the output calculated from RCPODS_WMO2006_Emissions_A1.prn. I'll truncate the file, and reread it and try it again. I've also forced pandas dataframe precision to be 4.

**Comment by znicholls** [comment]
Try adding `file_mhalo_emis="RCPODS_WMO2006_Emissions_RCP3PD.prn"` to your run call, does that change what you're seeing? 

For context, MAGICC runs with more than just the 23 gases in a SCEN file. There's also the gases defined in the prn files. Changing what's in the SCEN file (or pandas dataframe) won't change the emissions provided in the prn file.

**Comment by safiume** [comment]
Yep. It's being defined in RCPODS_WMO2006_Emissions_A1.prn, globally for all SCEN experiments per magcfg. I removed years 2026-2500. And I'm rerunning it now. I'll update this as soon as I have the output.

**Comment by safiume** [comment]
I've done a few things, but I can't seem to track down where the Fgasses are misset.

I've added the following to my magcfg: 
          'rf_total_constantafteryr' : 2350,
          'rf_tropoz_constantafteryr' : 2350,
          'rf_stratoz_constantafteryr' : 2350,
          'rf_mhalo_constantafteryr' : 2172,
          'rf_fgas_constantafteryr' : 2172,
          'mhalo_switch_conc2emis_yr' : 2008,
          'fgas_switchfromconc2emis_year': 2005,
          'n2o_switchfromconc2emis_year': 2005,

I've truncated the years to end at 2025 in RCPODS_WMO2006_Emissions_A1.prn file

I'm still getting the slight bump but I now longer see all the mhalo, only the fgasses. Which is totally strange since most of the Fgasses are set from the user scen.

I've updated the dev branch with the latest. I didn't copy over  RCPODS_WMO2006_Emissions_A1.prn.

**Comment by safiume** [comment]
Another oddity is that if I change the rf_mhalo and rf_fgas constantafteryr later than 2072 the code errors being unable to convert a very small value a decimal to -100 places to a float.

**Comment by safiume** [comment]
![image](https://user-images.githubusercontent.com/4840719/107114458-c8aab080-681a-11eb-9442-bca25ff1b7f0.png)

**Comment by znicholls** [comment]
I'm really confused. Can you write down a) what experiment you want to run b) how you're trying to run it c) what you're expecting to see (which outputs, which gases specifically) d) what you're actually seeing

**Comment by safiume** [comment]
The experiments are in https://github.com/hsbay/cdrmex/blob/dev/ONCtests.ipynb.

It looks like the FGases, N2O, CF4, C2F6, C6F14, SF6 aren't using the definitions in my custom SCENs.

![image](https://user-images.githubusercontent.com/4840719/107128850-e35e4300-6875-11eb-98de-64ea23f95d70.png)

**Comment by safiume** [comment]
I saved the experiment to a SCEN and ran it in MAGICC6 native (on wine on MacOS). I'm seeing the same issue. So, this isn't a pymagicc issue. I'd like to get in touch with someone on this however incase any of the logic is used for MAGICC7.
The gasses which have the ballooning concentration pulse after being forced to 0 or less are 'N2O', 'CF4', 'C2F6', 'C6F14', 'HFC143a', 'SF6'. This is after truncating part of RCPODS_WMO2006_Emissions_A1.prn.

**Comment by znicholls** [comment]
Can you post the scen file here please

**Comment by safiume** [comment]
This is the file I used but I had to change the suffix to txt for github.
[CCCx2050.SCEN.txt](https://github.com/openscm/pymagicc/files/5942640/CCCx2050.SCEN.txt)

**Comment by znicholls** [comment]
I just ran that file, I couldn't see anything wrong with the gases you refer to above (see plots below). In what year are you seeing the error?

![image](https://user-images.githubusercontent.com/23625371/107214213-afde0d00-6a5d-11eb-95de-c1c643b12506.png)
![image](https://user-images.githubusercontent.com/23625371/107214227-b5d3ee00-6a5d-11eb-99ba-77757c8dd75d.png)
![image](https://user-images.githubusercontent.com/23625371/107214244-bc626580-6a5d-11eb-951b-3c9240e7a69e.png)
![image](https://user-images.githubusercontent.com/23625371/107214267-c6846400-6a5d-11eb-9025-09093e9e7a4c.png)
![image](https://user-images.githubusercontent.com/23625371/107214288-cdab7200-6a5d-11eb-9438-970838fc4777.png)
![image](https://user-images.githubusercontent.com/23625371/107214308-d8660700-6a5d-11eb-975f-c53329e85d91.png)

**Comment by safiume** [comment]
I set the peak emissions for N2O in 2010, CF4 in 2010, C2F6 in 2020, HFC143a in 2020, SF6 in 2010, then they decline gently, then at 2029, I drop them by -90.  Are the values from pre 2029 from some other scen?
I forced those gasses to -90 for the year 2029 and 2030 to try and stop the pulse. Then for 2031-2100 I set them to 0.
I don't understand why it's rising in concentration for the gasses starting at 2005.

Looking at the temp graphs, I see a concentration pulse starting at 2028 - 2029, which drives up temperature response.
Whereas for CO2, CH4, and all the other ghgs, I can set them to 0 starting at 2029 and I don't see a weird spike in the previous year nor the successive years.

![image](https://user-images.githubusercontent.com/4840719/107217239-be2b1b00-69c2-11eb-8d8e-20517003b202.png)
![image](https://user-images.githubusercontent.com/4840719/107217273-cbe0a080-69c2-11eb-9f27-1c10a4d170f3.png)
![image](https://user-images.githubusercontent.com/4840719/107217324-e0249d80-69c2-11eb-960f-4135e15bb8cc.png)

**Comment by znicholls** [comment]
> Are the values from pre 2029 from some other scen?

All the plots I showed are concentrations. The emissions do what you have described. 

> I don't understand why it's rising in concentration for the gasses starting at 2005.

Emissions before 2005 are greater than zero hence concentrations continue to rise (the gases have fairly long lifetimes from memory so any emissions > 0 causes concentrations to rise).

> Looking at the temp graphs, I see a concentration pulse

You can't have a concentration pulse on a temperature graph. Do you mean you see a temperature spike in 2030? If yes, that is to be expected because your emissions file also causes emissions of all aerosol precursor species (BC, OC, SOx, NOx, NH3) to return immediately to zero in 2030. Such a rapid drop in emissions causes a spike in radiative forcing and hence in temperature.

> Whereas for CO2, CH4, and all the other ghgs, I can set them to 0 starting at 2029 and I don't see a weird spike in the previous year nor the successive years.

Correct, if you only set the GHGs to zero immediately then you don't get the aerosol radiative forcing spike nor the temperature spike. It is the fact that you are setting aerosol precursor species (BC, OC, SOx, NOx, NH3) to return immediately to zero in 2030 which is causing this temperature spike.

**Comment by safiume** [comment]
I see an over all temp spike and concentration increases when I set those gasses to 0 or -90. There's a larger spike at 0, than -90.

I don't get a spike from the other gasses like methane, it's only if I set those to zero. If I force them to trend down over longer periods of time, then there isn't a heat pulse.

Is this still something that's seen in MAGICC7? And is this behavior described in any other place beyond, WMO 2006 ODS: https://library.wmo.int/index.php?lvl=notice_display&id=6414#.YCGwg-CIbOQ, https://doi.org/10.5194/gmd-13-3571-2020?

**Comment by znicholls** [comment]
> those gasses

Which gases?

**Comment by safiume** [comment]
Just to clarify even if you have an emissions profile like so for N2O:
![image](https://user-images.githubusercontent.com/4840719/107287010-366efc00-6a16-11eb-9114-2a489d6f6a26.png)
(completely decreasing starting in 2005)

The resulting in orange is intended, with a peak in the late 2040s?
![image](https://user-images.githubusercontent.com/4840719/107287445-d2006c80-6a16-11eb-8329-23e9e4b314d9.png)

**Comment by znicholls** [comment]
> The resulting in orange is intended, with a peak in the late 2040s?

Correct. N2O's lifetime is fairly long so there is some lag between the start of the emissions decline in 2005 and the time at which concentrations peak around 2050.

**Comment by safiume** [comment]
Ok. Thanks
