### ISSUE TITLE
README contradicts itself regarding licensing

### ISSUE THREAD

**Issue by mikapfl** [openscm/pymagicc#336]
Hi,

in the first paragraph, the README.rst file states: "Pymagicc itself is AGPL licensed." However, later on in the [license paragraph](https://github.com/openscm/pymagicc/blob/master/README.rst#license), it states: "The pymagicc wrapper itself is released under a BSD-3 license.", which is also what the LICENSE file and badges say.

Cheers,

Mika

**Comment by rgieseke** [comment]
Good catch, thanks!

The wrapper license was indeed changed to BSD here: https://github.com/openscm/pymagicc/commit/44c098e244c6b35e592e131ab298e6fda4f5a248
